FROM relaysh/stdlib-trigger-json:latest
# WORKDIR /trigger
# COPY handler.py .
# CMD python handler.py

LABEL "org.opencontainers.image.title"="Lightstep IR Alert Created"
LABEL "org.opencontainers.image.description"="This trigger fires when a Lightstep IR alert triggers a response rule."
LABEL "com.puppet.nebula.sdk.version"="v1"
